---
- name: ensure nginx is installed
  apt: name=nginx

- name: ensure nginx default configuration is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: ensure nginx is started
  service: name=nginx state=started